### ISSUE TITLE
App Requirements

### ISSUE THREAD

**Issue by gjwgit** [anusii/msfatigue#1]
## Requirements

Capturing the requirements here

- [x] Support all platforms
  - [x] Support narrow (phone) layout
  - [x] Support wide (desktop) layout
- [x] Implement the 43 questions provided
  - [x] Read the questions from a formatted Markdown document
  - [x] Build the questionnaire from loading the Markdown document
- [x] Connect to POD for saving each session in a separate file
  - [x] Use `solidlogin` for Pod initialisation/connection
  - [x] On SUBMIT support saving locally or Pod (see rioconf)
  - [x] Each saved file will include a timestamp in the filename
- [x] GUI components
  - [x] Implement a Review tab for loading all completed surveys to be displayed in a compact form
  - [x] Implement an About button
  - [x] Implement integration testing

**Comment by zheyxu** [comment]
Current app status:
<img width="788" alt="Screenshot 2024-08-20 at 10 09 06 AM" src="https://github.com/user-attachments/assets/faaf880e-f483-44e8-bb6a-5970b7ef223c">

<img width="793" alt="Screenshot 2024-08-20 at 10 08 58 AM" src="https://github.com/user-attachments/assets/26ad65f8-1916-4a8a-b13b-df9799d531aa">

**Comment by zheyxu** [comment]
<img width="794" alt="Screenshot 2024-08-21 at 4 50 02 PM" src="https://github.com/user-attachments/assets/1b03860a-f64e-4f44-aedd-8fbc7454f5d2">
Add popup window.
